# Generated by Django 5.1.5 on 2025-01-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('codigo_convite', models.CharField(max_length=20, unique=True)),
                ('na_lista', models.BooleanField(default=False)),
                ('presenca_confirmada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='presentes/')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pagamento', models.CharField(default='pendente', max_length=20)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casamento.convidado')),
                ('presente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casamento.presente')),
            ],
        ),
    ]
