# Generated by Django 5.1.5 on 2025-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamento', '0002_presente_image_path_alter_presente_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presente',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
