# Generated by Django 5.1.5 on 2025-02-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamento', '0003_alter_presente_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('fisica', 'Física'), ('virtual', 'Virtual')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='presente',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casamento.loja'),
        ),
    ]
