# Generated by Django 5.1.5 on 2025-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamento', '0004_loja_presente_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presente',
            name='loja',
        ),
        migrations.AddField(
            model_name='presente',
            name='lojas',
            field=models.ManyToManyField(blank=True, to='casamento.loja'),
        ),
    ]
