# Generated by Django 5.1.5 on 2025-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamento', '0005_remove_presente_loja_presente_lojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='presente',
            name='link_compra',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
